// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chat"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chatmember"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/user"
)

// ChatMember is the model entity for the ChatMember schema.
type ChatMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatMemberQuery when eager-loading is set.
	Edges             ChatMemberEdges `json:"edges"`
	chat_members      *int
	user_chat_members *int
	selectValues      sql.SelectValues
}

// ChatMemberEdges holds the relations/edges for other nodes in the graph.
type ChatMemberEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Chat holds the value of the chat edge.
	Chat *Chat `json:"chat,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMemberEdges) ChatOrErr() (*Chat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: chat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmember.FieldIsAdmin:
			values[i] = new(sql.NullBool)
		case chatmember.FieldID:
			values[i] = new(sql.NullInt64)
		case chatmember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case chatmember.ForeignKeys[0]: // chat_members
			values[i] = new(sql.NullInt64)
		case chatmember.ForeignKeys[1]: // user_chat_members
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMember fields.
func (_m *ChatMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case chatmember.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case chatmember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field chat_members", value)
			} else if value.Valid {
				_m.chat_members = new(int)
				*_m.chat_members = int(value.Int64)
			}
		case chatmember.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_chat_members", value)
			} else if value.Valid {
				_m.user_chat_members = new(int)
				*_m.user_chat_members = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMember.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ChatMember entity.
func (_m *ChatMember) QueryUser() *UserQuery {
	return NewChatMemberClient(_m.config).QueryUser(_m)
}

// QueryChat queries the "chat" edge of the ChatMember entity.
func (_m *ChatMember) QueryChat() *ChatQuery {
	return NewChatMemberClient(_m.config).QueryChat(_m)
}

// Update returns a builder for updating this ChatMember.
// Note that you need to call ChatMember.Unwrap() before calling this method if this ChatMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMember) Update() *ChatMemberUpdateOne {
	return NewChatMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMember) Unwrap() *ChatMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMembers is a parsable slice of ChatMember.
type ChatMembers []*ChatMember
