// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chat"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chatmember"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/user"
)

// ChatMemberCreate is the builder for creating a ChatMember entity.
type ChatMemberCreate struct {
	config
	mutation *ChatMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJoinedAt sets the "joined_at" field.
func (_c *ChatMemberCreate) SetJoinedAt(v time.Time) *ChatMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *ChatMemberCreate) SetNillableJoinedAt(v *time.Time) *ChatMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetIsAdmin sets the "is_admin" field.
func (_c *ChatMemberCreate) SetIsAdmin(v bool) *ChatMemberCreate {
	_c.mutation.SetIsAdmin(v)
	return _c
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_c *ChatMemberCreate) SetNillableIsAdmin(v *bool) *ChatMemberCreate {
	if v != nil {
		_c.SetIsAdmin(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ChatMemberCreate) SetUserID(id int) *ChatMemberCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatMemberCreate) SetUser(v *User) *ChatMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (_c *ChatMemberCreate) SetChatID(id int) *ChatMemberCreate {
	_c.mutation.SetChatID(id)
	return _c
}

// SetChat sets the "chat" edge to the Chat entity.
func (_c *ChatMemberCreate) SetChat(v *Chat) *ChatMemberCreate {
	return _c.SetChatID(v.ID)
}

// Mutation returns the ChatMemberMutation object of the builder.
func (_c *ChatMemberCreate) Mutation() *ChatMemberMutation {
	return _c.mutation
}

// Save creates the ChatMember in the database.
func (_c *ChatMemberCreate) Save(ctx context.Context) (*ChatMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMemberCreate) SaveX(ctx context.Context) *ChatMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMemberCreate) defaults() {
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := chatmember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		v := chatmember.DefaultIsAdmin
		_c.mutation.SetIsAdmin(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMemberCreate) check() error {
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "ChatMember.joined_at"`)}
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`ent: missing required field "ChatMember.is_admin"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatMember.user"`)}
	}
	if len(_c.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "ChatMember.chat"`)}
	}
	return nil
}

func (_c *ChatMemberCreate) sqlSave(ctx context.Context) (*ChatMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMemberCreate) createSpec() (*ChatMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmember.Table, sqlgraph.NewFieldSpec(chatmember.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(chatmember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.IsAdmin(); ok {
		_spec.SetField(chatmember.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_chat_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chat_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMember.Create().
//		SetJoinedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMemberUpsert) {
//			SetJoinedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMemberCreate) OnConflict(opts ...sql.ConflictOption) *ChatMemberUpsertOne {
	_c.conflict = opts
	return &ChatMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMemberCreate) OnConflictColumns(columns ...string) *ChatMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMemberUpsertOne{
		create: _c,
	}
}

type (
	// ChatMemberUpsertOne is the builder for "upsert"-ing
	//  one ChatMember node.
	ChatMemberUpsertOne struct {
		create *ChatMemberCreate
	}

	// ChatMemberUpsert is the "OnConflict" setter.
	ChatMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetIsAdmin sets the "is_admin" field.
func (u *ChatMemberUpsert) SetIsAdmin(v bool) *ChatMemberUpsert {
	u.Set(chatmember.FieldIsAdmin, v)
	return u
}

// UpdateIsAdmin sets the "is_admin" field to the value that was provided on create.
func (u *ChatMemberUpsert) UpdateIsAdmin() *ChatMemberUpsert {
	u.SetExcluded(chatmember.FieldIsAdmin)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMemberUpsertOne) UpdateNewValues() *ChatMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.JoinedAt(); exists {
			s.SetIgnore(chatmember.FieldJoinedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatMemberUpsertOne) Ignore() *ChatMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMemberUpsertOne) DoNothing() *ChatMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMemberCreate.OnConflict
// documentation for more info.
func (u *ChatMemberUpsertOne) Update(set func(*ChatMemberUpsert)) *ChatMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsAdmin sets the "is_admin" field.
func (u *ChatMemberUpsertOne) SetIsAdmin(v bool) *ChatMemberUpsertOne {
	return u.Update(func(s *ChatMemberUpsert) {
		s.SetIsAdmin(v)
	})
}

// UpdateIsAdmin sets the "is_admin" field to the value that was provided on create.
func (u *ChatMemberUpsertOne) UpdateIsAdmin() *ChatMemberUpsertOne {
	return u.Update(func(s *ChatMemberUpsert) {
		s.UpdateIsAdmin()
	})
}

// Exec executes the query.
func (u *ChatMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatMemberUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatMemberUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatMemberCreateBulk is the builder for creating many ChatMember entities in bulk.
type ChatMemberCreateBulk struct {
	config
	err      error
	builders []*ChatMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatMember entities in the database.
func (_c *ChatMemberCreateBulk) Save(ctx context.Context) ([]*ChatMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMemberCreateBulk) SaveX(ctx context.Context) []*ChatMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMemberUpsert) {
//			SetJoinedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatMemberUpsertBulk {
	_c.conflict = opts
	return &ChatMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMemberCreateBulk) OnConflictColumns(columns ...string) *ChatMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMemberUpsertBulk{
		create: _c,
	}
}

// ChatMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatMember nodes.
type ChatMemberUpsertBulk struct {
	create *ChatMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMemberUpsertBulk) UpdateNewValues() *ChatMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.JoinedAt(); exists {
				s.SetIgnore(chatmember.FieldJoinedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatMemberUpsertBulk) Ignore() *ChatMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMemberUpsertBulk) DoNothing() *ChatMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMemberCreateBulk.OnConflict
// documentation for more info.
func (u *ChatMemberUpsertBulk) Update(set func(*ChatMemberUpsert)) *ChatMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsAdmin sets the "is_admin" field.
func (u *ChatMemberUpsertBulk) SetIsAdmin(v bool) *ChatMemberUpsertBulk {
	return u.Update(func(s *ChatMemberUpsert) {
		s.SetIsAdmin(v)
	})
}

// UpdateIsAdmin sets the "is_admin" field to the value that was provided on create.
func (u *ChatMemberUpsertBulk) UpdateIsAdmin() *ChatMemberUpsertBulk {
	return u.Update(func(s *ChatMemberUpsert) {
		s.UpdateIsAdmin()
	})
}

// Exec executes the query.
func (u *ChatMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
