// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chat"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chatmember"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/predicate"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/user"
)

// ChatMemberUpdate is the builder for updating ChatMember entities.
type ChatMemberUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMemberMutation
}

// Where appends a list predicates to the ChatMemberUpdate builder.
func (_u *ChatMemberUpdate) Where(ps ...predicate.ChatMember) *ChatMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *ChatMemberUpdate) SetIsAdmin(v bool) *ChatMemberUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *ChatMemberUpdate) SetNillableIsAdmin(v *bool) *ChatMemberUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ChatMemberUpdate) SetUserID(id int) *ChatMemberUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMemberUpdate) SetUser(v *User) *ChatMemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (_u *ChatMemberUpdate) SetChatID(id int) *ChatMemberUpdate {
	_u.mutation.SetChatID(id)
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *ChatMemberUpdate) SetChat(v *Chat) *ChatMemberUpdate {
	return _u.SetChatID(v.ID)
}

// Mutation returns the ChatMemberMutation object of the builder.
func (_u *ChatMemberUpdate) Mutation() *ChatMemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMemberUpdate) ClearUser() *ChatMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *ChatMemberUpdate) ClearChat() *ChatMemberUpdate {
	_u.mutation.ClearChat()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMemberUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMember.user"`)
	}
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMember.chat"`)
	}
	return nil
}

func (_u *ChatMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmember.Table, chatmember.Columns, sqlgraph.NewFieldSpec(chatmember.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(chatmember.FieldIsAdmin, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMemberUpdateOne is the builder for updating a single ChatMember entity.
type ChatMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMemberMutation
}

// SetIsAdmin sets the "is_admin" field.
func (_u *ChatMemberUpdateOne) SetIsAdmin(v bool) *ChatMemberUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *ChatMemberUpdateOne) SetNillableIsAdmin(v *bool) *ChatMemberUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ChatMemberUpdateOne) SetUserID(id int) *ChatMemberUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMemberUpdateOne) SetUser(v *User) *ChatMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (_u *ChatMemberUpdateOne) SetChatID(id int) *ChatMemberUpdateOne {
	_u.mutation.SetChatID(id)
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *ChatMemberUpdateOne) SetChat(v *Chat) *ChatMemberUpdateOne {
	return _u.SetChatID(v.ID)
}

// Mutation returns the ChatMemberMutation object of the builder.
func (_u *ChatMemberUpdateOne) Mutation() *ChatMemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMemberUpdateOne) ClearUser() *ChatMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *ChatMemberUpdateOne) ClearChat() *ChatMemberUpdateOne {
	_u.mutation.ClearChat()
	return _u
}

// Where appends a list predicates to the ChatMemberUpdate builder.
func (_u *ChatMemberUpdateOne) Where(ps ...predicate.ChatMember) *ChatMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMemberUpdateOne) Select(field string, fields ...string) *ChatMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMember entity.
func (_u *ChatMemberUpdateOne) Save(ctx context.Context) (*ChatMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMemberUpdateOne) SaveX(ctx context.Context) *ChatMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMemberUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMember.user"`)
	}
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMember.chat"`)
	}
	return nil
}

func (_u *ChatMemberUpdateOne) sqlSave(ctx context.Context) (_node *ChatMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmember.Table, chatmember.Columns, sqlgraph.NewFieldSpec(chatmember.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmember.FieldID)
		for _, f := range fields {
			if !chatmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(chatmember.FieldIsAdmin, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
