// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chat"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chatmember"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/message"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/user"
)

// ChatCreate is the builder for creating a Chat entity.
type ChatCreate struct {
	config
	mutation *ChatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ChatCreate) SetName(v string) *ChatCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsGroup sets the "is_group" field.
func (_c *ChatCreate) SetIsGroup(v bool) *ChatCreate {
	_c.mutation.SetIsGroup(v)
	return _c
}

// SetNillableIsGroup sets the "is_group" field if the given value is not nil.
func (_c *ChatCreate) SetNillableIsGroup(v *bool) *ChatCreate {
	if v != nil {
		_c.SetIsGroup(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatCreate) SetCreatedAt(v time.Time) *ChatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableCreatedAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatCreate) SetUpdatedAt(v time.Time) *ChatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableUpdatedAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ChatCreate) SetCreatorID(id int) *ChatCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_c *ChatCreate) SetNillableCreatorID(id *int) *ChatCreate {
	if id != nil {
		_c = _c.SetCreatorID(*id)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ChatCreate) SetCreator(v *User) *ChatCreate {
	return _c.SetCreatorID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ChatCreate) AddMessageIDs(ids ...int) *ChatCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ChatCreate) AddMessages(v ...*Message) *ChatCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the ChatMember entity by IDs.
func (_c *ChatCreate) AddMemberIDs(ids ...int) *ChatCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the ChatMember entity.
func (_c *ChatCreate) AddMembers(v ...*ChatMember) *ChatCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (_c *ChatCreate) Mutation() *ChatMutation {
	return _c.mutation
}

// Save creates the Chat in the database.
func (_c *ChatCreate) Save(ctx context.Context) (*Chat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatCreate) SaveX(ctx context.Context) *Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatCreate) defaults() {
	if _, ok := _c.mutation.IsGroup(); !ok {
		v := chat.DefaultIsGroup
		_c.mutation.SetIsGroup(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Chat.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := chat.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chat.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsGroup(); !ok {
		return &ValidationError{Name: "is_group", err: errors.New(`ent: missing required field "Chat.is_group"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chat.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chat.updated_at"`)}
	}
	return nil
}

func (_c *ChatCreate) sqlSave(ctx context.Context) (*Chat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatCreate) createSpec() (*Chat, *sqlgraph.CreateSpec) {
	var (
		_node = &Chat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chat.Table, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chat.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsGroup(); ok {
		_spec.SetField(chat.FieldIsGroup, field.TypeBool, value)
		_node.IsGroup = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.CreatorTable,
			Columns: []string{chat.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_created_chats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MembersTable,
			Columns: []string{chat.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chat.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatCreate) OnConflict(opts ...sql.ConflictOption) *ChatUpsertOne {
	_c.conflict = opts
	return &ChatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatCreate) OnConflictColumns(columns ...string) *ChatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatUpsertOne{
		create: _c,
	}
}

type (
	// ChatUpsertOne is the builder for "upsert"-ing
	//  one Chat node.
	ChatUpsertOne struct {
		create *ChatCreate
	}

	// ChatUpsert is the "OnConflict" setter.
	ChatUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ChatUpsert) SetName(v string) *ChatUpsert {
	u.Set(chat.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatUpsert) UpdateName() *ChatUpsert {
	u.SetExcluded(chat.FieldName)
	return u
}

// SetIsGroup sets the "is_group" field.
func (u *ChatUpsert) SetIsGroup(v bool) *ChatUpsert {
	u.Set(chat.FieldIsGroup, v)
	return u
}

// UpdateIsGroup sets the "is_group" field to the value that was provided on create.
func (u *ChatUpsert) UpdateIsGroup() *ChatUpsert {
	u.SetExcluded(chat.FieldIsGroup)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsert) SetUpdatedAt(v time.Time) *ChatUpsert {
	u.Set(chat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsert) UpdateUpdatedAt() *ChatUpsert {
	u.SetExcluded(chat.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatUpsertOne) UpdateNewValues() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chat.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatUpsertOne) Ignore() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatUpsertOne) DoNothing() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatCreate.OnConflict
// documentation for more info.
func (u *ChatUpsertOne) Update(set func(*ChatUpsert)) *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChatUpsertOne) SetName(v string) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateName() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateName()
	})
}

// SetIsGroup sets the "is_group" field.
func (u *ChatUpsertOne) SetIsGroup(v bool) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetIsGroup(v)
	})
}

// UpdateIsGroup sets the "is_group" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateIsGroup() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateIsGroup()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsertOne) SetUpdatedAt(v time.Time) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateUpdatedAt() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatCreateBulk is the builder for creating many Chat entities in bulk.
type ChatCreateBulk struct {
	config
	err      error
	builders []*ChatCreate
	conflict []sql.ConflictOption
}

// Save creates the Chat entities in the database.
func (_c *ChatCreateBulk) Save(ctx context.Context) ([]*Chat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatCreateBulk) SaveX(ctx context.Context) []*Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatUpsertBulk {
	_c.conflict = opts
	return &ChatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatCreateBulk) OnConflictColumns(columns ...string) *ChatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatUpsertBulk{
		create: _c,
	}
}

// ChatUpsertBulk is the builder for "upsert"-ing
// a bulk of Chat nodes.
type ChatUpsertBulk struct {
	create *ChatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatUpsertBulk) UpdateNewValues() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chat.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatUpsertBulk) Ignore() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatUpsertBulk) DoNothing() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatCreateBulk.OnConflict
// documentation for more info.
func (u *ChatUpsertBulk) Update(set func(*ChatUpsert)) *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChatUpsertBulk) SetName(v string) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateName() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateName()
	})
}

// SetIsGroup sets the "is_group" field.
func (u *ChatUpsertBulk) SetIsGroup(v bool) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetIsGroup(v)
	})
}

// UpdateIsGroup sets the "is_group" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateIsGroup() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateIsGroup()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsertBulk) SetUpdatedAt(v time.Time) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateUpdatedAt() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
