// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chat"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/chatmember"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/message"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/ent/user"
	"github.com/Hossara/quera_bootcamp_chatapp_backend/internal/repository/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescName is the schema descriptor for name field.
	chatDescName := chatFields[0].Descriptor()
	// chat.NameValidator is a validator for the "name" field. It is called by the builders before save.
	chat.NameValidator = chatDescName.Validators[0].(func(string) error)
	// chatDescIsGroup is the schema descriptor for is_group field.
	chatDescIsGroup := chatFields[1].Descriptor()
	// chat.DefaultIsGroup holds the default value on creation for the is_group field.
	chat.DefaultIsGroup = chatDescIsGroup.Default.(bool)
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[2].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescUpdatedAt is the schema descriptor for updated_at field.
	chatDescUpdatedAt := chatFields[3].Descriptor()
	// chat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chat.DefaultUpdatedAt = chatDescUpdatedAt.Default.(func() time.Time)
	// chat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chat.UpdateDefaultUpdatedAt = chatDescUpdatedAt.UpdateDefault.(func() time.Time)
	chatmemberFields := schema.ChatMember{}.Fields()
	_ = chatmemberFields
	// chatmemberDescJoinedAt is the schema descriptor for joined_at field.
	chatmemberDescJoinedAt := chatmemberFields[0].Descriptor()
	// chatmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	chatmember.DefaultJoinedAt = chatmemberDescJoinedAt.Default.(func() time.Time)
	// chatmemberDescIsAdmin is the schema descriptor for is_admin field.
	chatmemberDescIsAdmin := chatmemberFields[1].Descriptor()
	// chatmember.DefaultIsAdmin holds the default value on creation for the is_admin field.
	chatmember.DefaultIsAdmin = chatmemberDescIsAdmin.Default.(bool)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[0].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[1].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[2].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// messageDescIsEdited is the schema descriptor for is_edited field.
	messageDescIsEdited := messageFields[3].Descriptor()
	// message.DefaultIsEdited holds the default value on creation for the is_edited field.
	message.DefaultIsEdited = messageDescIsEdited.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
